// <auto-generated />
using System;
using AssignmentManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssignmentManagement.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssignmentManagement.Domain.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowResubmission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_resubmission");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MaxMarks")
                        .HasColumnType("integer")
                        .HasColumnName("max_marks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_assignment");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Assignments_ClassId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Assignments_Status");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("IX_Assignments_SubjectId");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_Assignments_TeacherId");

                    b.ToTable("assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignments_max_marks_positive", "\"max_marks\" > 0");
                        });
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_class");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollment");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollment_student_id");

                    b.HasIndex("ClassId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollments_ClassId_StudentId");

                    b.ToTable("enrollment", (string)null);
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subject");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Subjects_ClassId");

                    b.HasIndex("ClassId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Subjects_ClassId_Name");

                    b.ToTable("subject", (string)null);
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<string>("Feedback")
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<int?>("Marks")
                        .HasColumnType("integer")
                        .HasColumnName("marks");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<Guid?>("ReviewedByTeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_teacher_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Submitted")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_submission");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("IX_Submissions_AssignmentId");

                    b.HasIndex("ReviewedByTeacherId")
                        .HasDatabaseName("ix_submission_reviewed_by_teacher_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Submissions_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Submissions_StudentId");

                    b.HasIndex("AssignmentId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Submissions_AssignmentId_StudentId");

                    b.ToTable("submission", null, t =>
                        {
                            t.HasCheckConstraint("ck_submissions_marks_nonneg", "\"marks\" IS NULL OR \"marks\" >= 0");
                        });
                });

            modelBuilder.Entity("AssignmentManagement.Domain.TeacherClassSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("pk_teacher_class_subject");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_teacher_class_subject_class_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_teacher_class_subject_subject_id");

                    b.HasIndex("TeacherId", "ClassId", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_TeacherClassSubjects_TeacherId_ClassId_SubjectId");

                    b.ToTable("teacher_class_subject", (string)null);
                });

            modelBuilder.Entity("AssignmentManagement.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Assignment", b =>
                {
                    b.HasOne("AssignmentManagement.Domain.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_class_class_id");

                    b.HasOne("AssignmentManagement.Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_subject_subject_id");

                    b.HasOne("AssignmentManagement.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_user_teacher_id");
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Enrollment", b =>
                {
                    b.HasOne("AssignmentManagement.Domain.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_class_class_id");

                    b.HasOne("AssignmentManagement.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_enrollment_user_student_id");
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Subject", b =>
                {
                    b.HasOne("AssignmentManagement.Domain.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_class_class_id");
                });

            modelBuilder.Entity("AssignmentManagement.Domain.Submission", b =>
                {
                    b.HasOne("AssignmentManagement.Domain.Assignment", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submission_assignment_assignment_id");

                    b.HasOne("AssignmentManagement.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByTeacherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_submission_user_reviewed_by_teacher_id");

                    b.HasOne("AssignmentManagement.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_user_student_id");
                });

            modelBuilder.Entity("AssignmentManagement.Domain.TeacherClassSubject", b =>
                {
                    b.HasOne("AssignmentManagement.Domain.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_subject_class_class_id");

                    b.HasOne("AssignmentManagement.Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_subject_subject_subject_id");

                    b.HasOne("AssignmentManagement.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_class_subject_user_teacher_id");
                });
#pragma warning restore 612, 618
        }
    }
}
