<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AssignmentManagement.Application\AssignmentManagement.Application.csproj" />
    <ProjectReference Include="..\..\src\AssignmentManagement.Domain\AssignmentManagement.Domain.csproj" />
    <ProjectReference Include="..\..\src\AssignmentManagement.Infrastructure\AssignmentManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

</Project>
